services:
    rmcgirr83.newtopicsneedapproval.listener:
        class: rmcgirr83\newtopicsneedapproval\event\listener
        arguments:
            - '@auth'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
